apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  ROOT_PASSWORD: bXlwYXNzd29yZA==
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-access-keys
type: Opaque
data:
  AWS_ACCESS_KEY_ID: QUtJQVE3TkJXUFNRR1ZUTVRJRlY=
  AWS_SECRET_ACCESS_KEY: WW1DZWpXQnNuUXRYaWRQcTc1dlRpY1pXR0IzNzlRcC9xeHVZM2VBbw==
